INSERT INTO tb_users(name,email,salary) VALUES ('Maria','maria@gmail.com',1348.74);
INSERT INTO tb_users(name,email,salary) VALUES ('Joao Silva','joao@gmail.com',9276.62);
INSERT INTO tb_users(name,email,salary) VALUES ('Carlos Silva','carlos@gmail.com',7318.75);
INSERT INTO tb_users(name,email,salary) VALUES ('Adriana','adriana@gmail.com',10688.93);
INSERT INTO tb_users(name,email,salary) VALUES ('Karina','karina@gmail.com',7251.28);
INSERT INTO tb_users(name,email,salary) VALUES ('Carlos Marques','carlos@gmail.com',5485.79);
INSERT INTO tb_users(name,email,salary) VALUES ('Carlos Pereira','carlos@gmail.com',3519.41);
INSERT INTO tb_users(name,email,salary) VALUES ('Ana Maria','ana@gmail.com',2569.20);
INSERT INTO tb_users(name,email,salary) VALUES ('Beatriz','beatriz@gmail.com',3853.33);
INSERT INTO tb_users(name,email,salary) VALUES ('Joana','joana@gmail.com',4222.91);
INSERT INTO tb_users(name,email,salary) VALUES ('Tulio Augusto','tulio@gmail.com',9453.69);
INSERT INTO tb_users(name,email,salary) VALUES ('Augusto','augusto@gmail.com',4119.91);
INSERT INTO tb_users(name,email,salary) VALUES ('Marta','marta@gmail.com',4519.15);
INSERT INTO tb_users(name,email,salary) VALUES ('Silvio','silvio@gmail.com',5285.68);
INSERT INTO tb_users(name,email,salary) VALUES ('Washington','washington@gmail.com',6439.99);
INSERT INTO tb_users(name,email,salary) VALUES ('Teresa','teresa@gmail.com',8929.78);
INSERT INTO tb_users(name,email,salary) VALUES ('Luciano','luciano@gmail.com',3360.72);
INSERT INTO tb_users(name,email,salary) VALUES ('Fabiana','fabiana@gmail.com',2532.83);
INSERT INTO tb_users(name,email,salary) VALUES ('Fabio','fabio@gmail.com',5912.88);
INSERT INTO tb_users(name,email,salary) VALUES ('Gisele','gisele@gmail.com',7558.26);
INSERT INTO tb_users(name,email,salary) VALUES ('Larissa','larissa@gmail.com',2362.04);
INSERT INTO tb_users(name,email,salary) VALUES ('Natanael','natanael@gmail.com',6860.63);
INSERT INTO tb_users(name,email,salary) VALUES ('Meire','meire@gmail.com',3553.40);
INSERT INTO tb_users(name,email,salary) VALUES ('Ana Carolina','ana@gmail.com',1404.28);
INSERT INTO tb_users(name,email,salary) VALUES ('Filipe','filipe@gmail.com',3388.73);
